version: '3.9'

services:
  application:
    container_name: financ-back
    restart: always
    build:
      context: .
      target: develop
      dockerfile: Dockerfile
    environment:
      - PORT=3333
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - '3333:3333'
      - '9229:9229'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
