version: '3.9'

services:
  application:
    container_name: financ-api
    restart: always
    build:
      context: .
      # target: runtime
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
