import 'dotenv/config';

export const {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_STORAGE,
  FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_ID,
  FIREBASE_MEASUREMENT_ID,
  PORT,
} = process.env;
