import {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_ID,
  FIREBASE_MEASUREMENT_ID,
} from '../config';

export const firebaseConfig = {
  apiKey: FIREBASE_API_KEY,
  authDomain: FIREBASE_AUTH_DOMAIN,
  projectId: FIREBASE_PROJECT_ID,
  storageBucket: FIREBASE_STORAGE,
  messagingSenderId: FIREBASE_MESSAGING_SENDER_ID,
  appId: FIREBASE_ID,
  measurementId: FIREBASE_MEASUREMENT_ID,
};
